name: Run tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        env:
          MIGRATIONS_DIR: __test-migrations__
          CTF_SPACE_ID: ${{ secrets.TEST_SPACE_ID }}
          CTF_ENVIRONMENT_ID: ${{ secrets.CTF_ENVIRONMENT_ID }}
          CTF_CMA_TOKEN: ${{ secrets.CTF_CMA_TOKEN }}

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up node
              uses: actions/setup-node@v2
              with:
                node-version: '18.16.0'

            - name: Install dependencies
              run: npm install

            - name: Link binary
              run: npm link

            - name: Run tests
              run: npm test
