name: Run tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up node
              uses: actions/setup-node@v2
              with:
                node-version: '18.16.0'

            - name: Install dependencies
              run: npm install

            - name: Link binary
              run: npm link

            - name: Run tests
              run: npm test
              env:
                MIGRATIONS_DIR: __test-migrations__
                CTF_SPACE_ID: bo6ijs14u5ox
                CTF_ENVIRONMENT_ID: master
                CTF_CMA_TOKEN: dummy_token
